version: '3.9'
services:
  web:
      container_name: wordpress
      image: nginx
      build:
        context: ./etc/nginx
      ports:
        - "8000:80"
        - "3000:443"
      environment:
        - NGINX_HOST=${NGINX_HOST}
      volumes:
          - ./web:/var/www/html/public
          - ./etc/nginx/logs:/var/log/nginx
          - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./etc/nginx/sites/:/etc/nginx/sites-available
          - ./etc/nginx/conf.d/:/etc/nginx/conf.d
      restart: always
      
      depends_on:
        - php
        - db
      networks:
        - app-network
  php:
      build: 
        context: ./etc/php
      image: nanoninja/php-fpm
      ports:
        - 9000:9000
      restart: always
      volumes:
          - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
          - ./web:/var/www/html/public
      networks:
        - app-network
  db:
      image: mariadb
      container_name: ${MYSQL_HOST}
      restart: always
      env_file:
          - ".env"
      environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ALLOW_EMPTY_PASSWORD:yes
      ports:
          - 3306:3306
      volumes:
          - ./data/db/mysql:/var/lib/mysql
      networks:
        - app-network
  adminer:
      image: adminer
      ports:
          - 8080:8080
      restart: always
      networks:
        - app-network
      links:
        - db
networks:
  app-network:
    driver: bridge
